# Generated by Django 4.0.6 on 2023-06-07 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_Batch',
            },
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('complaint', models.TextField()),
                ('reply', models.TextField()),
            ],
            options={
                'db_table': 'tb_Complaints',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_Course',
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('hostel', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tb_Hostel',
            },
        ),
        migrations.CreateModel(
            name='Hostel_fee',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('electricity', models.IntegerField()),
                ('water', models.IntegerField()),
                ('food', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_Hostel_fee',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.TextField()),
                ('role', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_Login',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('last_pay_date', models.CharField(max_length=50)),
                ('next_pay_date', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_Payment',
            },
        ),
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('image', models.TextField()),
                ('email', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=15)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.login')),
            ],
            options={
                'db_table': 'tb_Warden',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.BigIntegerField()),
                ('image', models.CharField(max_length=150)),
                ('batch', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=150)),
                ('guardian_name', models.CharField(max_length=150)),
                ('guardian_number', models.CharField(max_length=150)),
                ('id_proof', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=15)),
                ('hostel_id', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.login')),
            ],
            options={
                'db_table': 'tb_Student',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor_number', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('beds', models.CharField(max_length=50)),
                ('vacancy', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=150)),
                ('h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.hostel')),
            ],
            options={
                'db_table': 'tb_Rooms',
            },
        ),
        migrations.CreateModel(
            name='Matron',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('image', models.TextField()),
                ('email', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('hostel_id', models.IntegerField()),
                ('password', models.CharField(max_length=15)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.login')),
            ],
            options={
                'db_table': 'tb_Matron',
            },
        ),
    ]
