# Generated by Django 3.2.7 on 2023-06-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='image',
        ),
    ]
