# Generated by Django 4.0.6 on 2023-06-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0002_remove_rooms_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='hostel_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
