# Generated by Django 4.0.6 on 2023-06-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0003_complaints_hostel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('hostel_id', models.IntegerField()),
                ('date', models.DateField()),
                ('no_of_days', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tb_Leave',
            },
        ),
        migrations.CreateModel(
            name='Outpass',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('hostel_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tb_Outpass',
            },
        ),
    ]
