# Generated by Django 4.0.6 on 2023-06-08 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0004_leave_outpass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='o_id',
            new_name='l_id',
        ),
    ]
