# Generated by Django 4.2.1 on 2023-06-12 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0007_payment_status_alter_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matron',
            name='password',
        ),
        migrations.RemoveField(
            model_name='students',
            name='password',
        ),
        migrations.RemoveField(
            model_name='warden',
            name='password',
        ),
    ]
