# Generated by Django 4.2.1 on 2023-06-19 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0008_remove_matron_password_remove_students_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel_fee',
            name='food',
        ),
        migrations.CreateModel(
            name='Mess_Fee',
            fields=[
                ('mf_id', models.AutoField(primary_key=True, serialize=False)),
                ('mess_fee', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.login')),
            ],
            options={
                'db_table': 'tb_Mess_Fee',
            },
        ),
    ]
