# Generated by Django 4.0.6 on 2023-07-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0010_rename_student_id_mess_fee_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='join_date',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
