# Generated by Django 4.0.6 on 2023-07-03 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0011_students_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.login'),
        ),
    ]
