# Generated by Django 4.0.6 on 2023-07-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0012_alter_payment_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='student_id',
            new_name='student',
        ),
    ]
